influence_settings:
  place_cost: 50
  break_cost: 30
  use_cost: 10

guild_settings:
  max_members: 5
  storage: 1000

settings:
  hide_players_spawn: false
  kingdom_ranks:
    ridder1:
      name: "Ridder 1"
      prefix: '&7[&fRidder &6I&7]'
    ridder2:
      name: "Ridder 2"
      prefix: '&7[&fRidder &6II&7]'
    ridder3:
      name: "Ridder 3"
      prefix: '&7[&fRidder &6III&7]'
    hertog:
      name: "Hertog"
      prefix: '&7[&2Hertog&7]'
    koning:
      name: "King"
      prefix: '&7[&6Koning&7]'
  hertog_perms:
    - ""
  king_perms:
    - ""
  home_timer: 10 # in seconds
  beta_mode: false
  use_materials:
    - "CHEST"
    - "LAVA_BUCKET"
    - "TRAP_DOOR"
    - "IRON_TRAPDOOR"
    - "STATIONARY_LAVA"
    - "LAVA"
    - "IRON_DOOR"
    - "TRAPPED_CHEST"
    - "SPRUCE_DOOR"
    - "DARK_OAK_DOOR"
    - "ACACIA_DOOR"
    - "JUNGLE_DOOR"
    - "BIRCH_DOOR"
    - "WOODEN_DOOR"
    - "WOOD_PLATE"
    - "STONE_PLATE"
    - "GOLD_PLATE"
    - "IRON_PLATE"
    - "WOOD_BUTTON"
    - "STONE_BUTTON"

mines:
  reset_after_seconds: 10
  regions:
    - ""

ender_chest:
  rank0:
    material: BARRIER
    data: 0
    display_name: "&c&lBLOCKED"
    permission: ""
    lore:
       - ""
       - "Rank0 is required for this slot"
    slots: [0, 1, 2, 3, 4, 5, 6, 7, 8]
  rank1:
    material: BARRIER
    data: 0
    display_name: "&c&lBLOCKED"
    permission: "rank1.enderchest"
    lore:
       - ""
       - "Rank1 is required for this slot"
    slots: [9, 10, 11, 12, 13, 14, 15, 16, 17]
  rank2:
    material: BARRIER
    data: 0
    display_name: "&c&lBLOCKED"
    permission: "rank2.enderchest"
    lore:
       - ""
       - "Rank2 is required for this slot"
    slots: [18, 19, 20, 21, 22, 23, 24, 25, 26]
  rank3:
    material: BARRIER
    data: 0
    display_name: "&c&lBLOCKED"
    permission: "rank3.enderchest"
    lore:
       - ""
       - "Rank3 is required for this slot"
    slots: [27, 28, 29, 30, 31, 32, 33, 34, 35]
  rank4:
    material: BARRIER
    data: 0
    display_name: "&c&lBLOCKED"
    permission: "rank2.enderchest"
    lore:
      - ""
      - "Rank4 is required for this slot"
    slots: [36, 37, 38, 39, 40, 41, 42, 43, 44]
  rank5:
    material: BARRIER
    data: 0
    display_name: "&c&lBLOCKED"
    permission: "rank5.enderchest"
    lore:
      - ""
      - "Rank5 is required for this slot"
    slots: [45, 46, 47, 48, 49, 50, 51, 52, 53]

donkey:
  speed: 0.3
  jump: 0.5
  health: 18
  countdown: 5
  enemyRadiusCheck: 60.0

title:
  top: "&7Kingdom"
  subtitle: "&f%kingdom%"

messages:
  death_message: "&7[%player_kingdom%&7] &7%player_kingdom_rank%&7&7%player% is verwond door &7[%killer_kingdom%&7]&7%killer_kingdom_rank%&7&7%killer%"
  donators_region: "&cThis region is donators only."
  auto_smelt:
    enabled: "&aAutosmelt has been enabled"
    disabled: "&cAutosmelt has been disabled"
  mines:
    right_clicked: "&dThis block will regenerate in %time%s"
  mount:
    no_kingdom: "&cYou cannot spawn a horse without a kingdom"
    unmounted: "&cYou unmounted."
    in_combat: "&cYou can't mount up in combat!"
    players_nearby: "&cYou can't mount while enemy players are nearby!"
    mounted: "&7Je hebt succesvol je horse gemount!"
    on_cooldown: "&7Mounten onderbroken!"
    not_your_horse: "&cThis is not your horse!"
    cant_damage_mounted: "&7You can't deal damage while mounted!"
    cant_damage_your_horse: "&7You can't damage your own horse!"
    cant_damage_your_kingdom: "&7You can't damage horses from your own kingdom!"
    got_umounted: "&cYou got unmounted!"
  regions:
    place: "&cYou can only place water buckets and cobweb here."
  events:
    bounty_hunters:
      capping: "&cYou are capping %zone%."
      capped: "&cYou have capped %zone% move to another one to continue."
      started_broadcast:
        - "&aEvent has started"
        - "  &7- &fBounty Hunters"
      winners_format: "&f%position%&7. &f%kingdom%"
      ended_broadcast:
        - "&cEvent has ended!"
        - "  - Winners"
        - "%format%"
    conquest:
      capping: "&cYou are capping %zone%."
      capped: "&cYou have capped %zone% and got a point move to another for another point."
      started_broadcast:
        - "&aEvent has started"
        - "  &7- &fConquest"
      ended_broadcast:
        - "&cEvent has ended!"
        - "  - Winners: %kingdom%"
        - "  - Last cap by %player%"
    break_the_core:
      started_broadcast:
        - "&aEvent has started"
        - "  &7- &fBreak the Core"
      ended_broadcast:
        - "&cEvent has ended!"
        - "  - Winners: %kingdom%"
        - "  - Last Break was by %player%"
    koth:
      capping: "&cYou are capping koth %koth%"
      started_broadcast:
        - "&aEvent has started"
        - "  &7- &fKoth %koth%"
      ended_broadcast:
        - "&cEvent has ended!"
        - "  - Winners: %kingdom%"
        - "  - Last Break was by %player%"
    war:
      started_broadcast:
        - "&aEvent has started"
        - "  &7- &fWar"
      winners_format: "&7%position%. &f%kingdom% &7- &f%kills% &7Kills"
      ended_broadcast:
        - "&cEvent has ended!"
        - "  - Winners: %kingdom%"
        - ""
        - "%format%"
  influence:
    type:
      breaking: "&cThis action costed you %influence%. New balance %new_influence%"
      interacting: "&cThis action costed you %influence%. New balance %new_influence%"
      placing: "&cThis action costed you %influence%. New balance %new_influence%"
  staff: 
    mode_enabled: "&6Staff Mode: &fEnabled"
    mode_disabled: "&6Staff Mode: &fDisabled"
    vanish_enabled: "&6Vanish: &fEnabled"
    vanish_disabled: "&6Vanish: &fDisabled"
    random_tp: "&aRandom teleported to %player%"
  freeze:
    player_frozen: "&aSpeler '%player%' is bevroren on %date%"
    player_unfrozen: "&cSpeler '%player%' is niet meer bevroren."
    player_bypass_freeze: "&cJe kunt deze speler niet bevriezen"
    logged_out: "&c&l[!!!!] &f%player% &clogged out while frozen!"
    damager_frozen: "&cYou cannot attack while frozen."
    victim_frozen: "&c%player% is frozen, you cannot attack him."
    cannot_do_while_frozen: "&cYou cannot do this while frozen!"
    message:
      - ""
      - "&cJe bent bevroren door een medewerker!"
      - "&7Join onze &fwachtruimte&7 en wacht rustig totdat je gesleeptwordt!"
      - "&f&lDiscord: &fdsc.gg/reforgedmc"
      - ""
      - "&7Je hebt 5 minuten. Uitloggen is een ban."
  tell_location:
    format: "[%x%, %y%, %z%]"
    waypoint:
      name: "%player%'s Location"
      color:
        r: 255
        g: 0
        b: 0
  stats:
    - "&6%player%"
    - ""
    - "&6Kills &f%kills%"
    - "&6Deaths &f%deaths%"
    - "&6Player KDR &f%kdr%"
    - "&6Influence &f%influence%"
    - "&6Kingdom &f%kingdom%"
  chat:
    has_been_muted: "&cThe chat has been muted by %player%"
    has_been_unmuted: "&cThe chat has been unmuted by %player%"
    chat_clear: "&cThe chat has been cleared by %player%"
    bypass_clear: "&aYou bypassed the chat clear because you've got a specific permission."
    muted: "&cThe chat is currently muted!"
    no_guild: "&cYou don't have a guild to chat with!"
    no_kingdom: "&cYou don't have a kingdom to chat, select one to have more features!"
    formats:
      guilds_chat: "%guild_name%%guild_tag% %prefix%%player%%suffix%&7: &f%message%"
      roleplay_chat: "&7[&4Roleplay&7] &7[%kingdom_name%&7] %prefix%%player%%suffix%&7: &f%message%"
      trade_chat: "&7[&6Trade&7] &7[%kingdom_name%&7] %prefix%%player%%suffix%&7: &f%message%"
      others_chat: "&7[&3Others&7] &7[%kingdom_name%&7] %prefix%%player%%suffix%&7: &f%message%"
      kingdom_chat: "&7[%kingdom_name%&7] &f%kingdom_rank% %prefix%%player%%suffix%&7: &f%message%"
  kingdom:
    help_op:
      - "Kingdom Help for ops"
    help_no_op:
      - "Kingdom help for no ops"
    unally:
      remove_request: "&cYour request to %kingdom% for being an alliance has been removed."
      not_ally: "&cYou are not ally with %kingdom%"
      broadcast:
        ally_removed: "&bYou are no longer ally with %kingdom%"
    ally:
      already_requested: "&cYou have already requested to this kingdom."
      already_ally: "&cAlready ally with that kingdom!"
      accepted_ally: "&bAlly with %kingdom% has been accepted!"   
      ally_requested: "&bYou have requested %kingdom% to be allies!"
      broadcast:
        requested_ally: "&b%kingdom% has requested you to be allies do /kingdom ally %kingdom% to accept!"
        ally_accepted: "&bAlly with %kingdom% has been accepted. Do /kingdom unally %kingdom% if you want to remove them."
    victim_teammate: "&2%player% &ais your teammate!"
    victim_ally: "&3%player% &bis an ally from &3%kingdom%"
    select_kingdom_before_continue: "&cPlease select an kingdom to continue playing with other players."
    set:
      target: "&eYour kingdom has been switched from %old_kingdom% to %new_kingdom%"
      broadcast: "&e%player% has switched their kingdom to %new_kingdom%!"
    top:
      format: "&7%position%. %kingdom% &7- &f%points%"
      message:
        - "&7Kingdom Top"
        - ""
        - "%format%"
    promote_target: "&aYou have been promoted from %oldrank% &ato %newrank%"
    demote_target: "&cYou have been demoted from %oldrank% &ato %newrank%"
  guild:
    help:
      - "Guild Help"
    already_in_guild: "&cYou are already in a guild."
    three_char: "&cYour tag needs to be exactly 3 characters."
    tag_taken: "&cThis tag is already taken."
    guild_taken: "&cGuild with that name already exists"
    created: "&aYour guild named %guild_name% has been created [%tag%]"
    created_broadcast: "&aGuild %guild_name% [%tag%] has been created by %player%."
    no_guild: "&cYou are not in a guild."
    only_leaders: "&cOnly the guild leader can do this."
    no_same_kingdom: "This player is not in the same kingdom as others in the guild."
    have_been_invited: "&aYou have been invited to join %guild_name% [%tag%]. Do /guild join %guild_name% to join."
    expired_invite: "&cYour invite to %guild_name% [%tag%] has expired!"
    already_invited: "&cThis player is already invited."
    guild_not_found: "&cGuild with that name does not exists."
    no_invite: "&cThis guild has not invited you."
    not_invited: "&cThis player is not invited."
    joined: "&aYou joined %guild_name% [%tag%]"
    not_from_guild: "&aThis player is not from your guild."
    cannot_kick_yourself: "&cYou cannot kick yourself."
    kicked: "&cYou have been kicked from %guild_name% [%tag%] by %player%"
    storage_full: "&cStorage is already full with influence you can't deposit right now."
    dont_have_influence: "&cYou don't have that much influence to deposit."
    deposit_filled: "&aYou only deposited %deposit% because the storage filled up!"
    deposit_added: "&aYou deposited %deposit% to the guild bank. Bank amount: %bank%"
    storage_empty: "&cStorage is empty theres nothing to withdraw."
    withdraw_emptied: "&aYou only withdrawed %withdraw% because the storage does not have that much."
    withdraw_added: "&aYou withdrawed %withdraw% from the guild bank. Bank amount: %bank%"
    guild_leave: "&cYou left %guild_name% [%tag%]"
    info:
      - "&7&l&m-----------------------------------------------"
      - ""
      - "%guild_name% [%tag%] [%online%/%max%]"
      - "&eLeader %leader%"
      - ""
      - "&eMembers %members%"
      - "&eInfluence Bank %bank%"
      - "&eKills %kills%"
      - "&eDeaths %deaths%"
      - "&eKDR %kdr%"
      - "&eKingdom %kingdom%"
      - "&7&l&m-----------------------------------------------"
    disband: "&cYour guild has been disbanded"
    guild_disbanded: "&cThe guild that you were in %guild_name% [%tag%] has been disbanded."
    guild_broadcast:
      player_joined: "&a%player% joined your guild."
      player_invited: "&a%player% invited %invited% to the guild."
      player_uninvited: "&a%uninvited% has been uninvited by %player%"
      player_kicked: "&a%kicked% has been kicked from the guild by %player%"
      player_deposited: "&a%player% deposited %deposit% influence to the bank. Bank amount: %bank%"
      player_withdrawed: "&a%player% withdrawed %withdraw% influence from the bank. Bank amount: %bank%"
      player_left: "&a%player% left the guild."

selector_menu:
  rows: 3
  title: "&7Select a kingdom to begin"
  fill:
    enabled: true
    material: STAINED_GLASS_PANE
    data: 0
    amount: 1
    display_name: "&d"
    lore:
      - ""
  items:
    0:
      material: PAPER
      data: 0
      amount: 1
      display_name: "&eKingdom &6Eredon"
      lore:
        - ""
      kingdom: "eredon"

scoreboard_settings:
  enabled: true
  title: "&cZusiqs Kingdom"
  store: "&7&ostore.zusiqs.nl"
  always_lines: true # At the top and at the end will add a gray lines
  always_store: true # Store before the last line
  no_kingdom_lines:
    - "&7You currently don't have"
    - "&7a kingdom!"
    - ""
    - "&7Choose from the selector"
    - ""
  has_kingdom_lines:
    - "&cKingdom"
    - "%kingdom%"
    - ""
    - "&cInfluence"
    - "%influence%"
    - ""
    - "&cLocatie"
    - "%location_kingdom%"
    - ""
  staffmode_lines:
    - "&cVanish"
    - "%vanish%"
    - ""
    - "&cInfluence"
    - "&%influence%"
    - ""
    - "&cOnline Spellers"
    - "%online_players%"
    - ""
  bountyhunters_lines:
    - "&c&lBounty Hunters"
    - ""
    - "1. %time_1% &7- %cappedBy_1%"
    - "2. %time_2% &7- %cappedBy_2%"
    - "3. %time_3% &7- %cappedBy_3%"
    - "4. %time_4% &7- %cappedBy_4%"
    - "5. %time_5% &7- %cappedBy_5%"
    - "6. %time_6% &7- %cappedBy_6%"
  conquest_lines:
    - "&c&lConquest"
    - "  &c&l1. %kingdom_1%&7: &f%points_1%"
    - "  &c&l2. %kingdom_2%&7: &f%points_2%"
    - "  &c&l3. %kingdom_3%&7: &f%points_3%"
    - ""
    - " &a%time_green% &7| &e%time_yellow%"
    - " &c%time_red% &7| &9%time_blue%"
    - ""
    - "&cInfluence"
    - "%influence%"
    - ""
  koth_lines:
    - "&cKoth"
    - "%koth_name%"
    - ""
    - "&cCoords"
    - "%koth_coords%"
    - ""
    - "&cCapping"
    - "%koth_capping%"
    - ""
    - "&cTime"
    - "%koth_time%"
    - ""
  btc_lines:
    - "&c&lBreak The Core"
    - ""
    - "  &c&l1. %kingdom_1%&7: &f%breaks_1%"
    - "  &c&l2. %kingdom_2%&7: &f%breaks_2%"
    - "  &c&l3. %kingdom_3%&7: &f%breaks_3%"
  war_lines:
    - "&c&lWar"
    - ""
    - "  &c&l1. %kingdom_1%&7: &f%kills_1%"
    - "  &c&l2. %kingdom_2%&7: &f%kills_2%"
    - "  &c&l3. %kingdom_3%&7: &f%kills_3%"
    - ""
    - "&cTotal Deaths: &f%total_deaths%"
    - "&4&lEnds in &4%time%"