name: Kingdom
author: nik4o
main: me.niko.kingdom.Kingdom
version: 1.0.0
commands:
  kingdom:
    aliases: [k]
  bountyhunters:
  btc:
  conquest:
  koth:
  war:
    aliases: [oorlog]
  freeze:
    aliases: [ss, screenshare]
  staffmode:
    aliases: [mod, hackermode, staff]
  chat:
  portal:
  mount:
  stats:
  guild:
    aliases: [guilds]
  list:
    aliases: [onlineplayers]
  telllocation:
    aliases: [tl]
  influence:
  setendexit:
  autosmelt:
  mines:
  creload:
    aliases: [reloadconfig, configreload]
  enderchest:
    aliases: [ec, echest]